task: denovo
dataset_name: massivekb
top_peaks: 300
pep_length:
- 0
- 100
buffer_size: 10000
denovo_tf:
  conf_threshold: 0
  batch_size: 32
  ref_batch_size: 32
  weight_decay: 1.0e-05
  epochs: 50
  subset: 0
  decoder_dropout: 0.0
  decoder_use_cls: false
  learning_rate: 0.0005
  warmup_steps: 100000
  cosine_period_steps: 1200000
  train_label_smoothing: 0.01
