"""DINO-family losses, heads, schedules, and multi-crop routing.

Adapted for mass spectra from the official DINO and DINOv2 implementations:
- DINO: https://github.com/facebookresearch/dino
- DINOv2: https://github.com/facebookresearch/dinov2

Names such as ``DINOHead`` and ``DINOLoss`` are retained to identify and credit
the upstream algorithms from which these components were adapted.
"""

import numpy as np
import torch.nn as nn
import math
import warnings
import torch
import torch.nn.functional as F
import torch.distributed as dist
from torch.nn.utils.parametrizations import weight_norm
from src.models.pooler import build_pooler


def cosine_scheduler(
    base_value,
    final_value,
    epochs,
    niter_per_ep,
    warmup_epochs=0,
    start_warmup_value=0.0,
):
    warmup_schedule = np.array([])
    warmup_iters = int(warmup_epochs * niter_per_ep)
    if warmup_epochs > 0:
        warmup_schedule = np.linspace(start_warmup_value, base_value, warmup_iters)

    iters = np.arange(epochs * niter_per_ep - warmup_iters)
    schedule = final_value + 0.5 * (base_value - final_value) * (
        1 + np.cos(math.pi * iters / len(iters))
    )
    schedule = np.concatenate((warmup_schedule, schedule))
    assert len(schedule) == epochs * niter_per_ep
    return schedule


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class DINOHead(nn.Module):
    def __init__(
        self,
        in_dim,
        out_dim,
        use_bn=False,
        norm_last_layer=True,
        nlayers=3,
        hidden_dim=2048,
        bottleneck_dim=256,
    ):
        super().__init__()
        nlayers = max(nlayers, 1)
        if nlayers == 1:
            self.mlp = nn.Linear(in_dim, bottleneck_dim)
        else:
            layers = [nn.Linear(in_dim, hidden_dim)]
            if use_bn:
                layers.append(nn.BatchNorm1d(hidden_dim))
            layers.append(nn.GELU())
            for _ in range(nlayers - 2):
                layers.append(nn.Linear(hidden_dim, hidden_dim))
                if use_bn:
                    layers.append(nn.BatchNorm1d(hidden_dim))
                layers.append(nn.GELU())
            layers.append(nn.Linear(hidden_dim, bottleneck_dim))
            self.mlp = nn.Sequential(*layers)
        self.apply(self._init_weights)
        self.last_layer = weight_norm(
            nn.Linear(bottleneck_dim, out_dim, bias=False)
        )
        self.last_layer.parametrizations.weight.original0.data.fill_(1)
        if norm_last_layer:
            self.last_layer.parametrizations.weight.original0.requires_grad = False

    def _load_from_state_dict(
        self,
        state_dict,
        prefix,
        local_metadata,
        strict,
        missing_keys,
        unexpected_keys,
        error_msgs,
    ):
        # PyTorch deprecated ``nn.utils.weight_norm`` in favor of the
        # parametrizations API. Preserve compatibility with checkpoints that
        # stored the old ``last_layer.weight_g`` / ``last_layer.weight_v`` keys.
        legacy_to_new = {
            f"{prefix}last_layer.weight_g": (
                f"{prefix}last_layer.parametrizations.weight.original0"
            ),
            f"{prefix}last_layer.weight_v": (
                f"{prefix}last_layer.parametrizations.weight.original1"
            ),
        }
        for legacy_key, new_key in legacy_to_new.items():
            if legacy_key in state_dict and new_key not in state_dict:
                state_dict[new_key] = state_dict[legacy_key]
                state_dict.pop(legacy_key)

        super()._load_from_state_dict(
            state_dict,
            prefix,
            local_metadata,
            strict,
            missing_keys,
            unexpected_keys,
            error_msgs,
        )

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=0.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)

    def forward_bottleneck(self, x):
        """Return the normalized feature immediately before the prototype layer.

        This is the feature used by the original DINO ``DINOHead.forward``
        immediately before ``last_layer``. It is exposed for downstream
        embedding evaluation only; training continues to use ``forward``.
        """
        x = self.mlp(x)
        x = nn.functional.normalize(x, dim=-1, p=2)
        return x

    def forward(self, x):
        return self.last_layer(self.forward_bottleneck(x))


class DINOLoss(nn.Module):
    """
    DINO class-token loss with official DINOv2 target centering modes.

    The Sinkhorn-Knopp path matches
    ``/path/to/work/dinov2/dinov2/loss/dino_clstoken_loss.py``
    ``DINOLoss.sinkhorn_knopp_teacher``. The EMA centering path preserves the
    existing dIon DINO behavior and corresponds to official
    ``DINOLoss.softmax_center_teacher`` plus ``update_center``.
    """

    def __init__(
        self,
        out_dim,
        num_crops_tot,
        warmup_teacher_temp,
        teacher_temp,
        warmup_teacher_temp_epochs,
        nepochs,
        student_temp=0.1,
        center_momentum=0.9,
        num_global_crops=2,
        centering="centering",
        sinkhorn_iterations=3,
    ):
        super().__init__()
        if centering not in {"centering", "sinkhorn_knopp"}:
            raise ValueError("centering must be 'centering' or 'sinkhorn_knopp'.")
        self.student_temp = student_temp
        self.center_momentum = center_momentum
        self.num_crops_tot = num_crops_tot
        self.num_global_crops = num_global_crops
        self.centering = centering
        self.sinkhorn_iterations = int(sinkhorn_iterations)
        self.register_buffer("center", torch.zeros(1, out_dim))
        # we apply a warm up for the teacher temperature because
        # a too high temperature makes the training instable at the beginning
        self.teacher_temp_schedule = np.concatenate(
            (
                np.linspace(
                    warmup_teacher_temp, teacher_temp, warmup_teacher_temp_epochs
                ),
                np.ones(nepochs - warmup_teacher_temp_epochs) * teacher_temp,
            )
        )

    @torch.no_grad()
    def sinkhorn_knopp_teacher(self, teacher_output, teacher_temp, n_iterations=None):
        """Official DINOv2 balanced assignment targets for class-token logits."""
        n_iterations = self.sinkhorn_iterations if n_iterations is None else n_iterations
        teacher_output = teacher_output.float()
        world_size = dist.get_world_size() if dist.is_initialized() else 1
        # Official notation: Q is K-by-B, where K is prototypes and B samples.
        q = torch.exp(teacher_output / teacher_temp).t()
        batch_size = q.shape[1] * world_size
        num_prototypes = q.shape[0]

        sum_q = torch.sum(q)
        if dist.is_initialized():
            dist.all_reduce(sum_q)
        q /= sum_q

        for _ in range(n_iterations):
            sum_of_rows = torch.sum(q, dim=1, keepdim=True)
            if dist.is_initialized():
                dist.all_reduce(sum_of_rows)
            q /= sum_of_rows
            q /= num_prototypes

            q /= torch.sum(q, dim=0, keepdim=True)
            q /= batch_size

        q *= batch_size
        return q.t()

    @torch.no_grad()
    def _teacher_targets(self, teacher_output, teacher_temp):
        if self.centering == "centering":
            teacher_out = F.softmax((teacher_output - self.center) / teacher_temp, dim=-1)
            self.update_center(teacher_output)
            return teacher_out
        if self.centering == "sinkhorn_knopp":
            return self.sinkhorn_knopp_teacher(teacher_output, teacher_temp)
        raise NotImplementedError(f"Unsupported centering mode: {self.centering}")

    def forward(
        self,
        student_output,
        teacher_output,
        epoch,
        teacher_temp=None,
        student_groups=None,
        student_group_weights=None,
        return_group_losses=False,
    ):
        """Cross-entropy between teacher and student prototype assignments.

        ``teacher_temp`` is an optional per-iteration override used by dIon
        DINOv2 to match official ``dinov2/train/train.py`` where
        ``teacher_temp_schedule[iteration]`` is passed into the loss. When it is
        omitted, the original DINO epoch-indexed schedule is preserved.

        ``student_groups`` and ``student_group_weights`` support dIon's
        hybrid precursor-null objective. They average all valid cross-view
        terms within each named student group, then apply the supplied group
        weights. Omitting both arguments preserves ordinary DINO/DINOv2 loss
        weighting exactly.
        """
        student_out = student_output / self.student_temp
        student_out = student_out.chunk(self.num_crops_tot)

        if (student_groups is None) != (student_group_weights is None):
            raise ValueError(
                "student_groups and student_group_weights must be provided together."
            )
        if student_groups is not None:
            if len(student_groups) != len(student_out):
                raise ValueError("student_groups must have one entry per student crop.")
            expected_groups = set(student_groups)
            supplied_groups = set(student_group_weights)
            if supplied_groups != expected_groups:
                raise ValueError(
                    "student_group_weights keys must exactly match student_groups."
                )
            if any(float(weight) < 0 for weight in student_group_weights.values()):
                raise ValueError("student_group_weights must be non-negative.")
            if abs(sum(float(weight) for weight in student_group_weights.values()) - 1.0) > 1e-8:
                raise ValueError("student_group_weights must sum to 1.")
            group_losses = {
                group: student_output.new_zeros(()) for group in expected_groups
            }
            group_counts = {group: 0 for group in expected_groups}
        else:
            total_loss = student_output.new_zeros(())
            n_loss_terms = 0

        if teacher_temp is None:
            temp = self.teacher_temp_schedule[
                min(epoch, len(self.teacher_temp_schedule) - 1)
            ]
        else:
            temp = float(teacher_temp)
        teacher_out = self._teacher_targets(teacher_output, temp).detach()
        teacher_out = teacher_out.chunk(self.num_global_crops)

        for iq, q in enumerate(teacher_out):
            for v in range(len(student_out)):
                if v == iq:
                    # We skip cases where student and teacher operate on the same view.
                    continue
                loss = torch.sum(-q * F.log_softmax(student_out[v], dim=-1), dim=-1)
                loss = loss.mean()
                if student_groups is None:
                    total_loss += loss
                    n_loss_terms += 1
                else:
                    group = student_groups[v]
                    group_losses[group] += loss
                    group_counts[group] += 1

        if student_groups is None:
            if n_loss_terms == 0:
                raise RuntimeError("DINO loss has no valid cross-view terms.")
            mean_loss = total_loss / n_loss_terms
            if return_group_losses:
                return mean_loss, {"all": mean_loss}
            return mean_loss

        total_loss = student_output.new_zeros(())
        mean_group_losses = {}
        for group, group_loss in group_losses.items():
            if group_counts[group] == 0:
                raise RuntimeError(f"DINO loss group {group!r} has no valid terms.")
            mean_group_losses[group] = group_loss / group_counts[group]
            total_loss += (
                float(student_group_weights[group])
                * mean_group_losses[group]
            )
        if return_group_losses:
            return total_loss, mean_group_losses
        return total_loss

    @torch.no_grad()
    def update_center(self, teacher_output):
        """
        Update center used for teacher output.
        """
        batch_center = torch.sum(teacher_output, dim=0, keepdim=True)
        if dist.is_initialized():
            dist.all_reduce(batch_center)
            world_size = dist.get_world_size()
        else:
            world_size = 1
        batch_center = batch_center / (len(teacher_output) * world_size)

        # ema update
        self.center = self.center * self.center_momentum + batch_center * (
            1 - self.center_momentum
        )


class DINOPatchLoss(nn.Module):
    """
    Spectrum adaptation of official DINOv2 ``iBOTPatchLoss``.

    Matches the control flow of
    ``/path/to/work/dinov2/dinov2/loss/ibot_patch_loss.py``:
    teacher logits are centered/sharpened, the loss is computed only on
    masked student tokens, and masked-token losses are weighted by the
    inverse number of masked tokens in each crop. Both official teacher target
    modes are supported: ``softmax_center_teacher``/EMA centering and
    ``sinkhorn_knopp_teacher`` balanced assignments.
    """

    def __init__(
        self,
        out_dim,
        warmup_teacher_temp,
        teacher_temp,
        warmup_teacher_temp_epochs,
        nepochs,
        student_temp=0.1,
        center_momentum=0.9,
        centering="centering",
        sinkhorn_iterations=3,
    ):
        super().__init__()
        if centering not in {"centering", "sinkhorn_knopp"}:
            raise ValueError("centering must be 'centering' or 'sinkhorn_knopp'.")
        self.student_temp = student_temp
        self.center_momentum = center_momentum
        self.centering = centering
        self.sinkhorn_iterations = int(sinkhorn_iterations)
        self.register_buffer("center", torch.zeros(1, out_dim))
        self.teacher_temp_schedule = np.concatenate(
            (
                np.linspace(
                    warmup_teacher_temp, teacher_temp, warmup_teacher_temp_epochs
                ),
                np.ones(nepochs - warmup_teacher_temp_epochs) * teacher_temp,
            )
        )

    @torch.no_grad()
    def sinkhorn_knopp_teacher(
        self,
        teacher_output,
        teacher_temp,
        n_masked_patches_tensor=None,
        n_iterations=None,
    ):
        """Official DINOv2 balanced assignment targets for masked iBOT logits."""
        n_iterations = self.sinkhorn_iterations if n_iterations is None else n_iterations
        teacher_output = teacher_output.float()
        q = torch.exp(teacher_output / teacher_temp).t()
        if n_masked_patches_tensor is None:
            batch_size = torch.tensor(float(q.shape[1]), device=q.device, dtype=q.dtype)
        elif torch.is_tensor(n_masked_patches_tensor):
            batch_size = n_masked_patches_tensor.to(device=q.device, dtype=q.dtype)
        else:
            batch_size = torch.tensor(
                float(n_masked_patches_tensor), device=q.device, dtype=q.dtype
            )
        if dist.is_initialized():
            dist.all_reduce(batch_size)
        num_prototypes = q.shape[0]

        sum_q = torch.sum(q)
        if dist.is_initialized():
            dist.all_reduce(sum_q)
        q /= sum_q

        for _ in range(n_iterations):
            sum_of_rows = torch.sum(q, dim=1, keepdim=True)
            if dist.is_initialized():
                dist.all_reduce(sum_of_rows)
            q /= sum_of_rows
            q /= num_prototypes

            q /= torch.sum(q, dim=0, keepdim=True)
            q /= batch_size

        q *= batch_size
        return q.t()

    @torch.no_grad()
    def _teacher_targets(self, teacher_masked, teacher_temp):
        if self.centering == "centering":
            teacher_probs = F.softmax((teacher_masked - self.center) / teacher_temp, dim=-1)
            self.update_center(teacher_masked)
            return teacher_probs
        if self.centering == "sinkhorn_knopp":
            n_masked = torch.tensor(
                teacher_masked.shape[0], device=teacher_masked.device, dtype=torch.float32
            )
            return self.sinkhorn_knopp_teacher(
                teacher_masked,
                teacher_temp=teacher_temp,
                n_masked_patches_tensor=n_masked,
            )
        raise NotImplementedError(f"Unsupported centering mode: {self.centering}")

    def forward(
        self,
        student_tokens,
        teacher_tokens,
        token_masks,
        epoch,
        teacher_temp=None,
    ):
        """
        Compute iBOT masked-token CE following ``iBOTPatchLoss.forward_masked``.

        ``teacher_temp`` is an optional per-iteration override used by dIon
        DINOv2 to match official ``dinov2/train/train.py`` where the current
        scheduled teacher temperature is passed into both DINO and iBOT losses.
        """
        if teacher_temp is None:
            temp = self.teacher_temp_schedule[
                min(epoch, len(self.teacher_temp_schedule) - 1)
            ]
        else:
            temp = float(teacher_temp)
        normalizer = 0
        student_masked = []
        teacher_masked = []
        masks_weight = []

        for student_view, teacher_view, mask in zip(
            student_tokens, teacher_tokens, token_masks
        ):
            normalizer += mask.shape[0]
            if not mask.any():
                continue

            # Official DINOv2 passes flat masked-token logits into
            # ``iBOTPatchLoss.forward_masked``. Keep dense-logit support for
            # compatibility, but the DINOv2 wrapper now uses this flat path.
            if student_view.ndim == 2:
                expected = int(mask.sum().item())
                if student_view.shape[0] != expected or teacher_view.shape[0] != expected:
                    raise ValueError(
                        "Flat iBOT logits must have one row per True entry in the dense mask."
                    )
                student_masked.append(student_view)
                teacher_masked.append(teacher_view)
            else:
                student_masked.append(student_view[mask])
                teacher_masked.append(teacher_view[mask])

            # Official DINOv2 ``masks_weight`` is inverse masked-token count
            # per crop, expanded to selected masked patch positions.
            masks_weight.append(
                (1 / mask.sum(-1).clamp(min=1.0))
                .unsqueeze(-1)
                .expand_as(mask)[mask]
            )

        if not teacher_masked:
            return torch.zeros((), device=self.center.device, dtype=self.center.dtype)

        student_masked = torch.cat(student_masked, dim=0)
        teacher_masked = torch.cat(teacher_masked, dim=0)
        masks_weight = torch.cat(masks_weight, dim=0)
        teacher_probs = self._teacher_targets(teacher_masked, temp).detach()
        token_loss = torch.sum(
            -teacher_probs * F.log_softmax(student_masked / self.student_temp, dim=-1),
            dim=-1,
        )
        total_loss = (token_loss * masks_weight).sum()
        return total_loss / normalizer

    @torch.no_grad()
    def update_center(self, teacher_output):
        batch_center = torch.sum(teacher_output, dim=0, keepdim=True)
        if dist.is_initialized():
            dist.all_reduce(batch_center)
            world_size = dist.get_world_size()
        else:
            world_size = 1
        batch_center = batch_center / (len(teacher_output) * world_size)
        self.center = self.center * self.center_momentum + batch_center * (
            1 - self.center_momentum
        )


class KoLeoLoss(nn.Module):
    """
    Matches official DINOv2 ``KoLeoLoss`` in
    ``dinov2/loss/koleo_loss.py``.

    The official code finds nearest neighbors by maximum inner product after
    L2 normalization, then applies a pairwise L2 distance and ``-log`` mean.
    """

    def __init__(self, eps=1e-8):
        super().__init__()
        self.eps = eps
        self.pdist = nn.PairwiseDistance(2, eps=eps)

    def pairwise_NNs_inner(self, x):
        """Official DINOv2 nearest-neighbor selection for normalized vectors."""
        dots = torch.mm(x, x.t())
        n = x.shape[0]
        dots.view(-1)[:: (n + 1)].fill_(-1)
        _, indices = torch.max(dots, dim=1)
        return indices

    def forward(self, features):
        if features.shape[0] <= 1:
            return torch.zeros((), device=features.device, dtype=features.dtype)

        with torch.amp.autocast(features.device.type, enabled=False):
            features = F.normalize(features, eps=self.eps, dim=-1, p=2)
            nn_indices = self.pairwise_NNs_inner(features)
            distances = self.pdist(features, features[nn_indices])
            return -torch.log(distances + self.eps).mean()


class MultiCropWrapper(nn.Module):
    """
    Perform forward pass separately on each resolution input.
    The inputs corresponding to a single resolution are clubbed and a single
    forward is run on the same resolution inputs. Hence, we do several
    forward passes = number of different resolutions used. We then
    concatenate all the output features and run the head forward on these
    concatenated features.
    """

    def __init__(
        self,
        backbone,
        head,
        pooling="cls",
        num_heads=8,
    ):
        super(MultiCropWrapper, self).__init__()
        self.backbone = backbone
        self.head = head

        _pool_options = [
            "cls",
            "average",
            "avg_frozen",
            "crossattend",
            "crossattend_cls",
        ]
        assert (
            pooling in _pool_options
        ), f"'{pooling}' not in supported options: {_pool_options}"
        if pooling == "cls" or pooling == "crossattend_cls":
            assert hasattr(
                backbone, "cls_token"
            ), "Backbone needs to have attribute CLS_token if pooling=cls"

        self.pooling = pooling
        self.num_heads = num_heads
        self.pooler = build_pooler(
            pooling=pooling,
            embedding_dim=backbone.running_units,
            num_heads=num_heads,
        )


    def _load_from_state_dict(
        self,
        state_dict,
        prefix,
        local_metadata,
        strict,
        missing_keys,
        unexpected_keys,
        error_msgs,
    ):
        # Backward compatibility for legacy checkpoints that stored pooling
        # parameters directly on MultiCropWrapper (proj/multihead_attn/cross_attend_token).
        legacy_to_new_prefixes = {
            "multihead_attn.": "pooler.multihead_attn.",
            "proj.": "pooler.projection.",
        }
        for legacy_suffix, new_suffix in legacy_to_new_prefixes.items():
            legacy_prefix = f"{prefix}{legacy_suffix}"
            new_prefix = f"{prefix}{new_suffix}"
            for key in [k for k in list(state_dict.keys()) if k.startswith(legacy_prefix)]:
                new_key = f"{new_prefix}{key[len(legacy_prefix):]}"
                if new_key not in state_dict:
                    state_dict[new_key] = state_dict[key]
                state_dict.pop(key)

        legacy_token_key = f"{prefix}cross_attend_token"
        new_token_key = f"{prefix}pooler.cross_attend_token"
        if legacy_token_key in state_dict:
            if new_token_key not in state_dict:
                state_dict[new_token_key] = state_dict[legacy_token_key]
            state_dict.pop(legacy_token_key)

        super()._load_from_state_dict(
            state_dict,
            prefix,
            local_metadata,
            strict,
            missing_keys,
            unexpected_keys,
            error_msgs,
        )

    def forward(self, x, mass=None, charge=None):
        """
        Args:
            x (list of tuples): Each tuple contains (sequences, padding_masks)
                                sequences: torch.Tensor of shape (batch_size, seq_len, embed_dim)
                                padding_masks: torch.Tensor of shape (batch_size, seq_len)
        """
        # Convert to list if not already
        if not isinstance(x, list):
            x = [x]


        padding = len(x[0]) > 1

        # Extract sequence lengths to group same resolution inputs
        seq_lengths = [inp[0].shape[1] for inp in x]

        idx_crops = torch.cumsum(
            torch.unique_consecutive(
                torch.tensor(seq_lengths),
                return_counts=True,
            )[1],
            0,
        )

        start_idx, output = 0, torch.empty(0).to(x[0][0].device)

        for end_idx in idx_crops:
            sequences = torch.cat([x[i][0] for i in range(start_idx, end_idx)])
            if padding:
                padding_masks = torch.cat([x[i][1] for i in range(start_idx, end_idx)])

            mass_slice = (
                torch.cat([mass[i] for i in range(start_idx, end_idx)])
                if mass is not None
                else None
            )

            charge_slice = (
                torch.cat([charge[i] for i in range(start_idx, end_idx)])
                if charge is not None
                else None
            )

            _out = self.backbone(
                sequences,
                key_padding_mask=padding_masks if padding else None,
                mass=mass_slice,
                charge=charge_slice,
            )
            embeds = _out["emb"]
            # These masks accomadate the new shape of embeds due to additional c/e/m or cls tokens
            out_masks = _out["mask"]

            embed = self.pooler(embeds, out_masks)

            # Accumulate outputs
            output = torch.cat((output, embed))
            start_idx = end_idx

        # Run the head forward on the concatenated features.
        return self.head(output)


class DINOv2MultiCropWrapper(nn.Module):
    """
    dIon analogue of official DINOv2 ``SSLMetaArch`` backbone/head routing.

    Official DINOv2 routes backbone outputs from global/local crops through a
    DINO class-token head and, for masked global crops, an iBOT patch-token
    head in ``dinov2/train/ssl_meta_arch.py``. This wrapper provides the same
    separation for spectra while reusing dIon's crop-length grouping instead
    of the official xFormers ``BlockDiagonalMask`` sequence packing.
    """

    def __init__(
        self,
        backbone,
        dino_head,
        ibot_head=None,
        pooling="cls",
        num_heads=8,
        ibot_rank_embedding_max_peaks=None,
    ):
        super().__init__()
        self.backbone = backbone
        self.dino_head = dino_head
        self.ibot_head = ibot_head

        _pool_options = [
            "cls",
            "average",
            "avg_frozen",
            "crossattend",
            "crossattend_cls",
        ]
        assert (
            pooling in _pool_options
        ), f"'{pooling}' not in supported options: {_pool_options}"
        if pooling == "cls" or pooling == "crossattend_cls":
            assert hasattr(
                backbone, "cls_token"
            ), "Backbone needs to have attribute CLS_token if pooling=cls"

        self.pooling = pooling
        self.num_heads = num_heads
        self.pooler = build_pooler(
            pooling=pooling,
            embedding_dim=backbone.running_units,
            num_heads=num_heads,
        )
        # Official DINOv2 ViT owns ``mask_token`` on the backbone and applies
        # it after patch embedding in ``prepare_tokens_with_masks``. dIon
        # applies the same embedding-space replacement through encoder hooks.
        # No-iBOT ablations do not apply token masks, so avoid registering an
        # otherwise-unused DDP parameter.
        if self.ibot_head is None:
            self.register_parameter("mask_token", None)
            self.register_parameter("mask_rank_embeddings", None)
        else:
            if ibot_rank_embedding_max_peaks is None:
                raise ValueError(
                    "iBOT requires ibot_rank_embedding_max_peaks to define the "
                    "physical peak-rank embedding table."
                )
            if int(ibot_rank_embedding_max_peaks) < 1:
                raise ValueError("ibot_rank_embedding_max_peaks must be positive.")
            self.mask_token = nn.Parameter(torch.zeros(1, backbone.running_units))
            self.mask_rank_embeddings = nn.Parameter(
                torch.empty(int(ibot_rank_embedding_max_peaks), backbone.running_units)
            )
            nn.init.trunc_normal_(self.mask_rank_embeddings, std=0.02)

    @property
    def ibot_out_dim(self):
        if self.ibot_head is None:
            raise RuntimeError("iBOT head is disabled for this DINOv2 wrapper.")
        return self.ibot_head.last_layer.out_features

    def _apply_ibot_head(self, tokens):
        if self.ibot_head is None:
            raise RuntimeError("iBOT head is disabled for this DINOv2 wrapper.")
        n_batch, n_tokens, dim = tokens.shape
        return self.ibot_head(tokens.reshape(n_batch * n_tokens, dim)).reshape(
            n_batch,
            n_tokens,
            -1,
        )

    def _apply_ibot_head_masked(self, crop_indices, peak_tokens, ibot_masks, patch_token_indices):
        """
        Official DINOv2-style masked iBOT head routing.

        Mirrors ``SSLMetaArch.forward_backward`` where ``x_norm_patchtokens``
        are flattened, masked positions are gathered with ``mask_indices_list``,
        and the iBOT head is applied only to that compact masked-token tensor.
        Here we keep per-crop outputs because dIon keeps crops as a list.
        """
        if self.ibot_head is None:
            raise RuntimeError("iBOT head is disabled for this DINOv2 wrapper.")
        selected_tokens = []
        selected_counts = []
        selected_crop_indices = []

        for crop_idx, crop_tokens, crop_mask in zip(
            crop_indices,
            peak_tokens.chunk(len(crop_indices), dim=0),
            ibot_masks.chunk(len(crop_indices), dim=0),
        ):
            if crop_idx not in patch_token_indices:
                continue
            count = int(crop_mask.sum().item())
            selected_crop_indices.append(crop_idx)
            selected_counts.append(count)
            if count > 0:
                selected_tokens.append(crop_tokens[crop_mask])

        if selected_tokens:
            selected_outputs = self.ibot_head(torch.cat(selected_tokens, dim=0))
        else:
            selected_outputs = peak_tokens.new_zeros((0, self.ibot_out_dim))

        outputs_by_crop = {}
        cursor = 0
        for crop_idx, count in zip(selected_crop_indices, selected_counts):
            if count > 0:
                outputs_by_crop[crop_idx] = selected_outputs[cursor : cursor + count]
                cursor += count
            else:
                outputs_by_crop[crop_idx] = peak_tokens.new_zeros((0, self.ibot_out_dim))
        return outputs_by_crop

    def forward(self, x, mass=None, charge=None):
        return self.forward_features(x, mass=mass, charge=charge)["dino_output"]

    def forward_features(
        self,
        x,
        mass=None,
        charge=None,
        return_patch_tokens=False,
        patch_token_indices=None,
        return_pooled=False,
        token_masks=None,
        ibot_masks=None,
        dino_crop_indices=None,
    ):
        """
        Args:
            x (list of tuples): Each tuple contains (sequences, padding_masks).
            patch_token_indices: Crop indices whose peak-token outputs should be
                returned. If None, all crops are returned when return_patch_tokens.
        """
        if not isinstance(x, list):
            x = [x]

        if token_masks is None:
            token_masks = [None] * len(x)
        elif not isinstance(token_masks, list):
            token_masks = [token_masks]
        if len(token_masks) != len(x):
            raise ValueError("token_masks must have one entry per crop.")

        if ibot_masks is None:
            ibot_masks = token_masks
        elif not isinstance(ibot_masks, list):
            ibot_masks = [ibot_masks]
        if len(ibot_masks) != len(x):
            raise ValueError("ibot_masks must have one entry per crop.")

        if dino_crop_indices is None:
            dino_crop_indices = tuple(range(len(x)))
        else:
            dino_crop_indices = tuple(dino_crop_indices)
        if not dino_crop_indices:
            raise ValueError("dino_crop_indices must not be empty.")
        if len(set(dino_crop_indices)) != len(dino_crop_indices):
            raise ValueError("dino_crop_indices must not contain duplicates.")
        if any(index < 0 or index >= len(x) for index in dino_crop_indices):
            raise ValueError("dino_crop_indices contains an out-of-range crop index.")

        padding = len(x[0]) > 1
        seq_lengths = [inp[0].shape[1] for inp in x]
        idx_crops = torch.cumsum(
            torch.unique_consecutive(
                torch.tensor(seq_lengths),
                return_counts=True,
            )[1],
            0,
        )

        if return_patch_tokens and self.ibot_head is None:
            raise RuntimeError("return_patch_tokens=True requires an iBOT head.")
        if patch_token_indices is None:
            patch_token_indices = set(range(len(x)))
        else:
            patch_token_indices = set(patch_token_indices)

        pooled_by_crop = {}
        patch_outputs = [None] * len(x)
        start_idx = 0

        for end_idx in idx_crops:
            end_idx = int(end_idx.item())
            crop_indices = list(range(start_idx, end_idx))
            sequences = torch.cat([x[i][0] for i in crop_indices])
            if padding:
                padding_masks = torch.cat([x[i][1] for i in crop_indices])

            group_token_masks = None
            if any(token_masks[i] is not None for i in crop_indices):
                masks_to_cat = []
                for i in crop_indices:
                    if token_masks[i] is None:
                        masks_to_cat.append(
                            torch.zeros(
                                x[i][0].shape[:2],
                                dtype=torch.bool,
                                device=x[i][0].device,
                            )
                        )
                    else:
                        masks_to_cat.append(token_masks[i])
                group_token_masks = torch.cat(masks_to_cat)

            group_ibot_masks = None
            if any(ibot_masks[i] is not None for i in crop_indices):
                masks_to_cat = []
                for i in crop_indices:
                    if ibot_masks[i] is None:
                        masks_to_cat.append(
                            torch.zeros(
                                x[i][0].shape[:2],
                                dtype=torch.bool,
                                device=x[i][0].device,
                            )
                        )
                    else:
                        masks_to_cat.append(ibot_masks[i])
                group_ibot_masks = torch.cat(masks_to_cat)

            mass_slice = (
                torch.cat([mass[i] for i in crop_indices])
                if mass is not None
                else None
            )
            charge_slice = (
                torch.cat([charge[i] for i in crop_indices])
                if charge is not None
                else None
            )

            backbone_kwargs = {
                "key_padding_mask": padding_masks if padding else None,
                "mass": mass_slice,
                "charge": charge_slice,
            }
            if group_token_masks is not None:
                if self.mask_token is None:
                    raise RuntimeError("token masks require an enabled iBOT mask token.")
                if not getattr(self.backbone, "supports_embedding_token_mask", False):
                    raise TypeError(
                        f"{type(self.backbone).__name__} does not expose the "
                        "embedding-space token-mask hook required by DINOv2."
                    )
                backbone_kwargs["token_mask"] = group_token_masks
                backbone_kwargs["mask_token"] = self.mask_token
                backbone_kwargs["mask_rank_embeddings"] = self.mask_rank_embeddings

            out = self.backbone(sequences, **backbone_kwargs)
            embeds = out["emb"]
            out_masks = out["mask"]
            pooled = self.pooler(embeds, out_masks)
            for crop_idx, crop_pooled in zip(
                crop_indices, pooled.chunk(len(crop_indices), dim=0)
            ):
                pooled_by_crop[crop_idx] = crop_pooled

            should_return_tokens = return_patch_tokens and any(
                idx in patch_token_indices for idx in crop_indices
            )
            if should_return_tokens:
                peak_tokens = embeds[:, out["num_cem_tokens"] :, :]
                if group_ibot_masks is None:
                    peak_outputs = self._apply_ibot_head(peak_tokens)
                    for crop_idx, crop_outputs in zip(
                        crop_indices, peak_outputs.chunk(len(crop_indices), dim=0)
                    ):
                        if crop_idx in patch_token_indices:
                            patch_outputs[crop_idx] = crop_outputs
                else:
                    # Official DINOv2 applies the iBOT head only to selected
                    # masked patch tokens, not to the full patch-token grid.
                    outputs_by_crop = self._apply_ibot_head_masked(
                        crop_indices,
                        peak_tokens,
                        group_ibot_masks,
                        patch_token_indices,
                    )
                    for crop_idx, crop_outputs in outputs_by_crop.items():
                        patch_outputs[crop_idx] = crop_outputs

            start_idx = end_idx

        # Auxiliary dense-only crops intentionally bypass the DINO head so they
        # cannot change its cross-view denominator, group weighting, or KoLeo.
        dino_pooled = torch.cat(
            [pooled_by_crop[index] for index in dino_crop_indices], dim=0
        )
        features = {"dino_output": self.dino_head(dino_pooled)}
        if return_patch_tokens:
            features["patch_outputs"] = patch_outputs
        if return_pooled:
            features["pooled_output"] = dino_pooled
        return features
